# Generated by Django 3.1.2 on 2020-10-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=10, unique=True)),
                ('bookTitle', models.CharField(max_length=100)),
                ('yearOfPublication', models.PositiveIntegerField(max_length=4)),
                ('publisher', models.CharField(max_length=70)),
            ],
        ),
    ]
