# Generated by Django 3.1.2 on 2020-10-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='yearOfPublication',
            field=models.PositiveIntegerField(),
        ),
    ]
