# Generated by Django 3.1.2 on 2020-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201007_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookAuthor',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='imageUrlL',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='imageUrlM',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='imageUrlS',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
