# Generated by Django 3.1.2 on 2020-10-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201007_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='imageUrlL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='imageUrlM',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='imageUrlS',
            field=models.URLField(blank=True),
        ),
    ]
