# Generated by Django 3.1.2 on 2020-10-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_userrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='userrating',
            index_together=set(),
        ),
    ]
