# Generated by Django 3.1.2 on 2020-10-08 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_auto_20201008_1714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'book')},
        ),
        migrations.AlterIndexTogether(
            name='userrating',
            index_together={('user', 'book')},
        ),
    ]
